// ============================================================================
// AIHub - Mock Data for Development
// This data mirrors the seed.sql for client-side rendering before Supabase
// ============================================================================

import type {
  Category,
  Tool,
  Comparison,
  ComparisonFeature,
  Prompt,
  PromptCategory,
  Tutorial,
  TutorialCategory,
  UseCase,
  Ranking,
  RankingEntry,
  NewsArticle,
  ToolPricing,
} from "@/types";

// ============================================================================
// CATEGORIES
// ============================================================================
export const categories: Category[] = [
  { id: "c1", name: "Text Generation", slug: "text-generation", description: "AI tools for generating text, articles, and written content", icon: "FileText", color: "#6366f1", parent_id: null, tool_count: 4, sort_order: 1, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c2", name: "Image Generation", slug: "image-generation", description: "AI tools for creating and editing images", icon: "Image", color: "#ec4899", parent_id: null, tool_count: 4, sort_order: 2, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c3", name: "Video Generation", slug: "video-generation", description: "AI tools for creating and editing videos", icon: "Video", color: "#f59e0b", parent_id: null, tool_count: 2, sort_order: 3, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c4", name: "Code Assistant", slug: "code-assistant", description: "AI tools for coding, debugging, and development", icon: "Code", color: "#10b981", parent_id: null, tool_count: 3, sort_order: 4, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c5", name: "Chatbots", slug: "chatbots", description: "AI chatbots and conversational AI tools", icon: "MessageSquare", color: "#3b82f6", parent_id: null, tool_count: 2, sort_order: 5, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c6", name: "Audio & Music", slug: "audio-music", description: "AI tools for audio generation and music creation", icon: "Music", color: "#8b5cf6", parent_id: null, tool_count: 2, sort_order: 6, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c7", name: "Productivity", slug: "productivity", description: "AI tools to boost productivity and workflow", icon: "Zap", color: "#f97316", parent_id: null, tool_count: 2, sort_order: 7, is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c8", name: "Marketing", slug: "marketing", description: "AI tools for marketing, SEO, and growth", icon: "TrendingUp", color: "#06b6d4", parent_id: null, tool_count: 1, sort_order: 8, is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c9", name: "Design", slug: "design", description: "AI tools for design and creative work", icon: "Palette", color: "#e11d48", parent_id: null, tool_count: 1, sort_order: 9, is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c10", name: "Data & Analytics", slug: "data-analytics", description: "AI tools for data analysis and insights", icon: "BarChart3", color: "#0ea5e9", parent_id: null, tool_count: 1, sort_order: 10, is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c11", name: "Education", slug: "education", description: "AI tools for learning and education", icon: "GraduationCap", color: "#14b8a6", parent_id: null, tool_count: 1, sort_order: 11, is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "c12", name: "Research", slug: "research", description: "AI tools for research and knowledge discovery", icon: "Search", color: "#a855f7", parent_id: null, tool_count: 1, sort_order: 12, is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
];

// ============================================================================
// TOOLS
// ============================================================================
export const tools: Tool[] = [
  { id: "t1", name: "ChatGPT", slug: "chatgpt", tagline: "AI-powered conversational assistant by OpenAI", description: "ChatGPT is an AI language model developed by OpenAI that can engage in conversational dialogue, answer questions, write content, debug code, and assist with a wide range of tasks.", logo_url: null, screenshot_url: null, website_url: "https://chat.openai.com", category_id: "c1", pricing_type: "freemium", starting_price: 20, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.8, review_count: 2847, upvote_count: 15420, view_count: 892340, bookmark_count: 5600, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t2", name: "Claude", slug: "claude", tagline: "Safe and helpful AI assistant by Anthropic", description: "Claude is an AI assistant created by Anthropic, designed to be helpful, harmless, and honest. It excels at analysis, writing, coding, math, and reasoning tasks.", logo_url: null, screenshot_url: null, website_url: "https://claude.ai", category_id: "c1", pricing_type: "freemium", starting_price: 20, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.75, review_count: 1923, upvote_count: 12350, view_count: 654210, bookmark_count: 4200, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t3", name: "Gemini", slug: "gemini", tagline: "Google's most capable AI model", description: "Gemini is Google's most capable AI model, designed to be multimodal from the ground up. It can understand and combine text, code, audio, image, and video.", logo_url: null, screenshot_url: null, website_url: "https://gemini.google.com", category_id: "c1", pricing_type: "freemium", starting_price: 19.99, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.6, review_count: 1456, upvote_count: 9870, view_count: 543200, bookmark_count: 3100, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t4", name: "Jasper", slug: "jasper", tagline: "AI content platform for enterprise marketing teams", description: "Jasper is an AI content generation platform designed for marketing teams. It helps create blog posts, social media content, ads, and emails.", logo_url: null, screenshot_url: null, website_url: "https://jasper.ai", category_id: "c1", pricing_type: "paid", starting_price: 49, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.3, review_count: 892, upvote_count: 5430, view_count: 234500, bookmark_count: 1200, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t5", name: "Midjourney", slug: "midjourney", tagline: "AI image generation through Discord", description: "Midjourney is an AI-powered image generation tool that creates stunning artwork from text descriptions. Known for its exceptional artistic quality.", logo_url: null, screenshot_url: null, website_url: "https://midjourney.com", category_id: "c2", pricing_type: "paid", starting_price: 10, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.85, review_count: 3210, upvote_count: 18900, view_count: 1023400, bookmark_count: 7800, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t6", name: "DALL-E 3", slug: "dall-e-3", tagline: "OpenAI's advanced image generation model", description: "DALL-E 3 is OpenAI's latest image generation model, integrated into ChatGPT. It creates highly detailed and accurate images from text descriptions.", logo_url: null, screenshot_url: null, website_url: "https://openai.com/dall-e-3", category_id: "c2", pricing_type: "freemium", starting_price: 20, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.65, review_count: 1876, upvote_count: 11200, view_count: 678900, bookmark_count: 4500, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t7", name: "Stable Diffusion", slug: "stable-diffusion", tagline: "Open-source AI image generation", description: "Stable Diffusion is an open-source AI image generation model that can be run locally, giving users full control over the generation process.", logo_url: null, screenshot_url: null, website_url: "https://stability.ai", category_id: "c2", pricing_type: "open_source", starting_price: 0, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.5, review_count: 2340, upvote_count: 14500, view_count: 890120, bookmark_count: 6200, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t8", name: "Leonardo AI", slug: "leonardo-ai", tagline: "AI image generation for game assets and creative production", description: "Leonardo AI is a generative AI platform focused on creating production-quality visual assets for games, marketing, and creative projects.", logo_url: null, screenshot_url: null, website_url: "https://leonardo.ai", category_id: "c2", pricing_type: "freemium", starting_price: 12, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.4, review_count: 1234, upvote_count: 7800, view_count: 432100, bookmark_count: 2800, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t9", name: "Runway", slug: "runway", tagline: "AI-powered creative suite for video", description: "Runway is an applied AI research company that builds next-generation creative tools. Their Gen-2 model enables text-to-video and advanced video editing.", logo_url: null, screenshot_url: null, website_url: "https://runway.ml", category_id: "c3", pricing_type: "freemium", starting_price: 15, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.55, review_count: 987, upvote_count: 8900, view_count: 456700, bookmark_count: 3200, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t10", name: "Synthesia", slug: "synthesia", tagline: "AI video generation with digital avatars", description: "Synthesia is an AI video creation platform that generates professional videos with AI avatars.", logo_url: null, screenshot_url: null, website_url: "https://synthesia.io", category_id: "c3", pricing_type: "paid", starting_price: 29, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.35, review_count: 654, upvote_count: 5600, view_count: 321000, bookmark_count: 1800, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t11", name: "GitHub Copilot", slug: "github-copilot", tagline: "AI pair programmer by GitHub", description: "GitHub Copilot is an AI coding assistant that helps you write code faster with suggestions, entire functions, and code from natural language.", logo_url: null, screenshot_url: null, website_url: "https://github.com/features/copilot", category_id: "c4", pricing_type: "paid", starting_price: 10, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.7, review_count: 2456, upvote_count: 16700, view_count: 789000, bookmark_count: 5400, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t12", name: "Cursor", slug: "cursor", tagline: "AI-first code editor", description: "Cursor is an AI-powered code editor built on VS Code that integrates AI deeply into the coding workflow.", logo_url: null, screenshot_url: null, website_url: "https://cursor.sh", category_id: "c4", pricing_type: "freemium", starting_price: 20, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.75, review_count: 1890, upvote_count: 13400, view_count: 567800, bookmark_count: 4100, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t13", name: "Replit", slug: "replit", tagline: "AI-powered collaborative coding platform", description: "Replit is an online IDE with AI capabilities that lets you code, collaborate, and deploy from your browser.", logo_url: null, screenshot_url: null, website_url: "https://replit.com", category_id: "c4", pricing_type: "freemium", starting_price: 7, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.25, review_count: 1234, upvote_count: 8900, view_count: 432100, bookmark_count: 2600, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t14", name: "Perplexity AI", slug: "perplexity-ai", tagline: "AI-powered answer engine", description: "Perplexity AI is an AI-powered search and answer engine that provides accurate, sourced answers to questions.", logo_url: null, screenshot_url: null, website_url: "https://perplexity.ai", category_id: "c5", pricing_type: "freemium", starting_price: 20, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.65, review_count: 1567, upvote_count: 11200, view_count: 543200, bookmark_count: 3800, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t15", name: "Character.AI", slug: "character-ai", tagline: "Create and chat with AI characters", description: "Character.AI lets you create and interact with AI-powered characters with distinct personalities.", logo_url: null, screenshot_url: null, website_url: "https://character.ai", category_id: "c5", pricing_type: "freemium", starting_price: 9.99, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.2, review_count: 2345, upvote_count: 9800, view_count: 678900, bookmark_count: 3400, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t16", name: "ElevenLabs", slug: "elevenlabs", tagline: "AI voice synthesis and cloning", description: "ElevenLabs is a leading AI voice technology company offering realistic text-to-speech, voice cloning, and audio AI tools.", logo_url: null, screenshot_url: null, website_url: "https://elevenlabs.io", category_id: "c6", pricing_type: "freemium", starting_price: 5, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.7, review_count: 1890, upvote_count: 12300, view_count: 567800, bookmark_count: 4000, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t17", name: "Suno", slug: "suno", tagline: "AI music generation", description: "Suno is an AI music generation platform that creates complete songs with vocals, instruments, and lyrics from text prompts.", logo_url: null, screenshot_url: null, website_url: "https://suno.com", category_id: "c6", pricing_type: "freemium", starting_price: 10, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.45, review_count: 987, upvote_count: 7600, view_count: 345600, bookmark_count: 2200, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t18", name: "Notion AI", slug: "notion-ai", tagline: "AI-powered workspace and knowledge management", description: "Notion AI integrates AI capabilities directly into the Notion workspace for writing, summarizing, and organizing.", logo_url: null, screenshot_url: null, website_url: "https://notion.so", category_id: "c7", pricing_type: "freemium", starting_price: 10, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.5, review_count: 1678, upvote_count: 10200, view_count: 543200, bookmark_count: 3600, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t19", name: "Otter.ai", slug: "otter-ai", tagline: "AI meeting transcription and notes", description: "Otter.ai is an AI-powered meeting assistant that provides real-time transcription, automated meeting notes, and action items.", logo_url: null, screenshot_url: null, website_url: "https://otter.ai", category_id: "c7", pricing_type: "freemium", starting_price: 16.99, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.35, review_count: 890, upvote_count: 5400, view_count: 234500, bookmark_count: 1500, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t20", name: "Copy.ai", slug: "copy-ai", tagline: "AI-powered marketing copy generator", description: "Copy.ai uses AI to generate marketing copy, blog posts, product descriptions, and social media content.", logo_url: null, screenshot_url: null, website_url: "https://copy.ai", category_id: "c8", pricing_type: "freemium", starting_price: 49, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.15, review_count: 765, upvote_count: 4300, view_count: 198700, bookmark_count: 900, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t21", name: "Canva AI", slug: "canva-ai", tagline: "AI-powered design platform", description: "Canva AI brings artificial intelligence to the popular design platform with Magic Design, text-to-image, and more.", logo_url: null, screenshot_url: null, website_url: "https://canva.com", category_id: "c9", pricing_type: "freemium", starting_price: 12.99, currency: "USD", is_featured: true, is_verified: true, is_published: true, avg_rating: 4.55, review_count: 2100, upvote_count: 11800, view_count: 678900, bookmark_count: 4800, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t22", name: "Julius AI", slug: "julius-ai", tagline: "AI data analysis and visualization", description: "Julius AI lets you analyze data, create visualizations, and generate insights using natural language.", logo_url: null, screenshot_url: null, website_url: "https://julius.ai", category_id: "c10", pricing_type: "freemium", starting_price: 20, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.3, review_count: 456, upvote_count: 3200, view_count: 123400, bookmark_count: 800, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t23", name: "Khanmigo", slug: "khanmigo", tagline: "AI tutor powered by GPT-4", description: "Khanmigo is Khan Academy's AI-powered tutoring assistant that provides personalized tutoring across subjects.", logo_url: null, screenshot_url: null, website_url: "https://khanacademy.org", category_id: "c11", pricing_type: "freemium", starting_price: 4, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.4, review_count: 567, upvote_count: 4500, view_count: 234500, bookmark_count: 1100, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
  { id: "t24", name: "Consensus", slug: "consensus", tagline: "AI-powered academic research search", description: "Consensus is an AI search engine that finds and synthesizes answers from scientific research papers.", logo_url: null, screenshot_url: null, website_url: "https://consensus.app", category_id: "c12", pricing_type: "freemium", starting_price: 9.99, currency: "USD", is_featured: false, is_verified: true, is_published: true, avg_rating: 4.35, review_count: 345, upvote_count: 2800, view_count: 123400, bookmark_count: 600, submitted_by: null, meta_title: null, meta_description: null, og_image_url: null, created_at: "2024-01-01", updated_at: "2024-01-01", published_at: "2024-01-01" },
];

// ============================================================================
// TOOL PRICING
// ============================================================================
export const toolPricing: ToolPricing[] = [
  { id: "tp1", tool_id: "t1", plan_name: "Free", price: 0, currency: "USD", billing_period: "monthly", features: ["GPT-3.5 access", "Limited messages", "Web browsing"], is_popular: false, sort_order: 1, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp2", tool_id: "t1", plan_name: "Plus", price: 20, currency: "USD", billing_period: "monthly", features: ["GPT-4 access", "DALL-E 3", "Advanced Data Analysis", "Custom GPTs", "Priority access"], is_popular: true, sort_order: 2, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp3", tool_id: "t1", plan_name: "Team", price: 25, currency: "USD", billing_period: "monthly", features: ["Everything in Plus", "Higher limits", "Admin console", "Team workspace"], is_popular: false, sort_order: 3, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp4", tool_id: "t1", plan_name: "Enterprise", price: null, currency: "USD", billing_period: "custom", features: ["Everything in Team", "Unlimited access", "SSO & SCIM", "Custom data retention"], is_popular: false, sort_order: 4, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp5", tool_id: "t2", plan_name: "Free", price: 0, currency: "USD", billing_period: "monthly", features: ["Claude 3 Haiku", "Limited messages", "Basic features"], is_popular: false, sort_order: 1, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp6", tool_id: "t2", plan_name: "Pro", price: 20, currency: "USD", billing_period: "monthly", features: ["Claude 3.5 Sonnet", "5x more usage", "Priority access", "Projects"], is_popular: true, sort_order: 2, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp7", tool_id: "t5", plan_name: "Basic", price: 10, currency: "USD", billing_period: "monthly", features: ["~200 images/month", "3 concurrent jobs", "Community gallery"], is_popular: false, sort_order: 1, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp8", tool_id: "t5", plan_name: "Standard", price: 30, currency: "USD", billing_period: "monthly", features: ["15 hrs Fast GPU", "Unlimited Relax", "Stealth mode"], is_popular: true, sort_order: 2, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tp9", tool_id: "t5", plan_name: "Pro", price: 60, currency: "USD", billing_period: "monthly", features: ["30 hrs Fast GPU", "Unlimited Relax", "Stealth mode", "12 concurrent jobs"], is_popular: false, sort_order: 3, created_at: "2024-01-01", updated_at: "2024-01-01" },
];

// ============================================================================
// PROMPT CATEGORIES
// ============================================================================
export const promptCategories: PromptCategory[] = [
  { id: "pc1", name: "Image Prompts", slug: "image-prompts", description: "Prompts for AI image generation tools", icon: "Image", color: "#ec4899", prompt_count: 3, sort_order: 1, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "pc2", name: "Video Prompts", slug: "video-prompts", description: "Prompts for AI video generation", icon: "Video", color: "#f59e0b", prompt_count: 2, sort_order: 2, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "pc3", name: "Writing Prompts", slug: "writing-prompts", description: "Prompts for content writing and copywriting", icon: "PenTool", color: "#6366f1", prompt_count: 1, sort_order: 3, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "pc4", name: "Coding Prompts", slug: "coding-prompts", description: "Prompts for code generation and debugging", icon: "Code", color: "#10b981", prompt_count: 3, sort_order: 4, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "pc5", name: "Business Prompts", slug: "business-prompts", description: "Prompts for business strategy and planning", icon: "Briefcase", color: "#0ea5e9", prompt_count: 1, sort_order: 5, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "pc6", name: "Marketing Prompts", slug: "marketing-prompts", description: "Prompts for marketing and SEO content", icon: "TrendingUp", color: "#f97316", prompt_count: 2, sort_order: 6, created_at: "2024-01-01", updated_at: "2024-01-01" },
];

// ============================================================================
// PROMPTS
// ============================================================================
export const prompts: Prompt[] = [
  { id: "p1", title: "Cinematic Landscape Photography", slug: "cinematic-landscape-photography", description: "Generate stunning cinematic landscape photographs", prompt_text: "Create a cinematic landscape photograph of [SUBJECT] during [TIME OF DAY]. The scene should feature [WEATHER/ATMOSPHERE] with dramatic lighting. Shot on a Sony A7R IV with a 24-70mm f/2.8 lens, shallow depth of field, golden hour lighting, 8K resolution, photorealistic, award-winning photography.", example_output: "A breathtaking cinematic photograph of rolling Tuscan hills during golden hour.", category_id: "pc1", tool_id: "t5", author_id: null, tags: ["photography", "landscape", "cinematic", "midjourney"], difficulty: "intermediate", use_count: 3420, save_count: 1230, upvote_count: 890, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "p2", title: "Product Photography on White", slug: "product-photography-white", description: "Professional product shots on clean backgrounds", prompt_text: "Professional product photography of [PRODUCT] on a clean white background. Studio lighting, soft shadows, high-end commercial photography style, 4K resolution, minimalist composition.", example_output: "A sleek wireless headphone photographed with perfect studio lighting.", category_id: "pc1", tool_id: "t5", author_id: null, tags: ["product", "commercial", "photography"], difficulty: "beginner", use_count: 2890, save_count: 980, upvote_count: 720, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "p3", title: "Blog Post Outline Generator", slug: "blog-post-outline-generator", description: "Generate comprehensive blog post outlines", prompt_text: 'Create a detailed blog post outline for the topic: "[TOPIC]". Include an attention-grabbing headline, meta description, introduction hook, 5-7 main sections with H2 headings, key points, and FAQ section.', example_output: 'A comprehensive outline for "10 AI Tools That Will Transform Your Workflow"', category_id: "pc3", tool_id: "t1", author_id: null, tags: ["blog", "seo", "content", "writing"], difficulty: "beginner", use_count: 5670, save_count: 2340, upvote_count: 1560, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-20", updated_at: "2024-01-20" },
  { id: "p4", title: "React Component Generator", slug: "react-component-generator", description: "Generate production-ready React components", prompt_text: "Create a production-ready React component for [COMPONENT]. Requirements: TypeScript, Tailwind CSS, responsive, accessible, with proper error handling and tests.", example_output: "A fully typed, accessible React component with tests.", category_id: "pc4", tool_id: "t1", author_id: null, tags: ["react", "typescript", "component"], difficulty: "advanced", use_count: 4230, save_count: 1890, upvote_count: 1340, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-01", updated_at: "2024-02-01" },
  { id: "p5", title: "Social Media Video Script", slug: "social-media-video-script", description: "Create engaging short-form video scripts", prompt_text: "Write a [DURATION]-second video script for [PLATFORM] about [TOPIC]. Include hook, problem statement, solution, key points, and CTA.", example_output: "A 60-second TikTok script about AI productivity hacks.", category_id: "pc2", tool_id: "t1", author_id: null, tags: ["video", "social media", "script"], difficulty: "beginner", use_count: 3450, save_count: 1450, upvote_count: 980, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-05", updated_at: "2024-02-05" },
  { id: "p6", title: "Email Marketing Campaign", slug: "email-marketing-campaign", description: "Design high-converting email sequences", prompt_text: "Design a [NUMBER]-email marketing sequence for [PRODUCT]. Include subject lines, preview text, email body, CTA, and send timing.", example_output: "A 5-email welcome sequence with A/B tested subject lines.", category_id: "pc6", tool_id: "t1", author_id: null, tags: ["email", "marketing", "conversion"], difficulty: "intermediate", use_count: 2780, save_count: 1120, upvote_count: 870, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-10", updated_at: "2024-02-10" },
  { id: "p7", title: "API Design Document", slug: "api-design-document", description: "Create comprehensive REST API documentation", prompt_text: "Design a REST API for [APPLICATION]. Include endpoints, schemas, authentication, rate limiting, and OpenAPI specification.", example_output: "A complete REST API specification for a task management app.", category_id: "pc4", tool_id: "t1", author_id: null, tags: ["api", "rest", "documentation"], difficulty: "advanced", use_count: 1890, save_count: 780, upvote_count: 560, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-15", updated_at: "2024-02-15" },
  { id: "p8", title: "Fantasy Character Portrait", slug: "fantasy-character-portrait", description: "Generate detailed fantasy character art", prompt_text: "Create a detailed fantasy character portrait of a [RACE/CLASS] character with [FEATURES], wearing [CLOTHING], in [SETTING]. Art style: [STYLE]. Highly detailed, masterwork quality, 4K.", example_output: "A majestic elven mage with silver hair and glowing blue eyes.", category_id: "pc1", tool_id: "t5", author_id: null, tags: ["fantasy", "character", "portrait", "art"], difficulty: "intermediate", use_count: 4560, save_count: 2100, upvote_count: 1680, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-20", updated_at: "2024-02-20" },
  { id: "p9", title: "Business Plan Executive Summary", slug: "business-plan-executive-summary", description: "Generate professional executive summaries", prompt_text: "Write an executive summary for [BUSINESS NAME], a [TYPE] that [VALUE PROP]. Include overview, problem, solution, market, revenue model, and projections.", example_output: "A compelling executive summary for a B2B SaaS startup.", category_id: "pc5", tool_id: "t1", author_id: null, tags: ["business", "startup", "planning"], difficulty: "intermediate", use_count: 2340, save_count: 890, upvote_count: 670, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-03-01", updated_at: "2024-03-01" },
  { id: "p10", title: "SEO Keyword Research", slug: "seo-keyword-research", description: "Comprehensive keyword research analysis", prompt_text: "Perform comprehensive keyword research for [NICHE]. Provide primary keywords, long-tail variations, question-based keywords, and content strategy.", example_output: "A detailed keyword research report for the AI tools niche.", category_id: "pc6", tool_id: "t1", author_id: null, tags: ["seo", "keywords", "research"], difficulty: "intermediate", use_count: 3120, save_count: 1560, upvote_count: 1120, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-03-05", updated_at: "2024-03-05" },
  { id: "p11", title: "Python Data Pipeline", slug: "python-data-pipeline", description: "Build robust data processing pipelines", prompt_text: "Create a Python data pipeline for [SOURCE] with extraction, transformation, loading, error handling, logging, and Docker containerization.", example_output: "A production-ready ETL pipeline with error handling.", category_id: "pc4", tool_id: "t1", author_id: null, tags: ["python", "data", "pipeline"], difficulty: "advanced", use_count: 1560, save_count: 670, upvote_count: 490, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-03-10", updated_at: "2024-03-10" },
  { id: "p12", title: "Explainer Video Storyboard", slug: "explainer-video-storyboard", description: "Create detailed video storyboards", prompt_text: "Create a storyboard for a [DURATION]-minute explainer video about [TOPIC]. Include scene descriptions, voiceover scripts, and transition notes.", example_output: "An 8-scene storyboard for a 2-minute SaaS product explainer.", category_id: "pc2", tool_id: "t1", author_id: null, tags: ["video", "storyboard", "explainer"], difficulty: "intermediate", use_count: 1890, save_count: 780, upvote_count: 560, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-03-15", updated_at: "2024-03-15" },
];

// ============================================================================
// TUTORIAL CATEGORIES
// ============================================================================
export const tutorialCategories: TutorialCategory[] = [
  { id: "tc1", name: "Getting Started", slug: "getting-started", description: "Beginner guides to AI tools", icon: "BookOpen", color: "#6366f1", tutorial_count: 2, sort_order: 1, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tc2", name: "Advanced Techniques", slug: "advanced-techniques", description: "Advanced AI usage patterns", icon: "Sparkles", color: "#ec4899", tutorial_count: 1, sort_order: 2, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tc3", name: "Workflow Automation", slug: "workflow-automation", description: "Automate workflows with AI", icon: "Workflow", color: "#10b981", tutorial_count: 1, sort_order: 3, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tc4", name: "AI for Business", slug: "ai-for-business", description: "Using AI to grow your business", icon: "Building2", color: "#f59e0b", tutorial_count: 1, sort_order: 4, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "tc5", name: "Prompt Engineering", slug: "prompt-engineering", description: "Master prompt engineering", icon: "MessageSquare", color: "#8b5cf6", tutorial_count: 1, sort_order: 5, created_at: "2024-01-01", updated_at: "2024-01-01" },
];

// ============================================================================
// TUTORIALS
// ============================================================================
export const tutorials: Tutorial[] = [
  { id: "tu1", title: "Getting Started with ChatGPT: A Complete Beginner's Guide", slug: "getting-started-chatgpt-beginners-guide", excerpt: "Learn everything you need to know to start using ChatGPT effectively.", content: "# Getting Started with ChatGPT\n\nChatGPT has revolutionized how we interact with AI...", cover_image_url: null, category_id: "tc1", author_id: null, difficulty: "beginner", read_time_minutes: 12, tags: ["chatgpt", "beginner", "guide"], related_tool_ids: ["t1"], view_count: 45600, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-15", updated_at: "2024-01-15", published_at: "2024-01-15" },
  { id: "tu2", title: "Mastering Midjourney: From Basic to Advanced Prompting", slug: "mastering-midjourney-prompting-guide", excerpt: "A comprehensive guide to creating stunning AI art with Midjourney.", content: "# Mastering Midjourney\n\nMidjourney has become the gold standard...", cover_image_url: null, category_id: "tc2", author_id: null, difficulty: "intermediate", read_time_minutes: 18, tags: ["midjourney", "image generation", "art"], related_tool_ids: ["t5"], view_count: 34500, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-20", updated_at: "2024-01-20", published_at: "2024-01-20" },
  { id: "tu3", title: "Building AI-Powered Workflows with Zapier and ChatGPT", slug: "ai-powered-workflows-zapier-chatgpt", excerpt: "Learn how to automate repetitive tasks with AI.", content: "# AI-Powered Workflow Automation\n\nAutomation is the key to scaling...", cover_image_url: null, category_id: "tc3", author_id: null, difficulty: "intermediate", read_time_minutes: 15, tags: ["automation", "zapier", "workflow"], related_tool_ids: ["t1"], view_count: 23400, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-01", updated_at: "2024-02-01", published_at: "2024-02-01" },
  { id: "tu4", title: "AI Content Strategy: How to 10x Your Content Output", slug: "ai-content-strategy-10x-output", excerpt: "Discover how businesses are using AI to dramatically increase content production.", content: "# 10x Your Content with AI\n\nContent is king...", cover_image_url: null, category_id: "tc4", author_id: null, difficulty: "beginner", read_time_minutes: 10, tags: ["content", "strategy", "marketing"], related_tool_ids: ["t1", "t4"], view_count: 18900, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-10", updated_at: "2024-02-10", published_at: "2024-02-10" },
  { id: "tu5", title: "The Complete Guide to Prompt Engineering", slug: "complete-guide-prompt-engineering", excerpt: "Master the art and science of prompt engineering.", content: "# The Complete Guide to Prompt Engineering\n\nPrompt engineering is the skill of the decade...", cover_image_url: null, category_id: "tc5", author_id: null, difficulty: "intermediate", read_time_minutes: 20, tags: ["prompt engineering", "techniques"], related_tool_ids: ["t1", "t2"], view_count: 56700, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-15", updated_at: "2024-02-15", published_at: "2024-02-15" },
  { id: "tu6", title: "GitHub Copilot: The Developer's Complete Handbook", slug: "github-copilot-developers-handbook", excerpt: "Everything developers need to know about GitHub Copilot.", content: "# GitHub Copilot Handbook\n\nGitHub Copilot has changed how developers write code...", cover_image_url: null, category_id: "tc1", author_id: null, difficulty: "intermediate", read_time_minutes: 14, tags: ["github copilot", "coding", "development"], related_tool_ids: ["t11"], view_count: 28900, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-03-01", updated_at: "2024-03-01", published_at: "2024-03-01" },
];

// ============================================================================
// USE CASES
// ============================================================================
export const useCases: UseCase[] = [
  { id: "uc1", title: "AI Tools for Students: The Ultimate Study Companion", slug: "ai-tools-for-students", excerpt: "Discover how students are using AI to study smarter and ace their exams.", content: "", cover_image_url: null, audience: "students", icon: "GraduationCap", related_tool_ids: ["t1", "t23", "t24"], tags: ["students", "education"], view_count: 34500, is_featured: true, is_published: true, meta_title: null, meta_description: null, author_id: null, created_at: "2024-01-20", updated_at: "2024-01-20", published_at: "2024-01-20" },
  { id: "uc2", title: "AI for Teachers: Enhancing Classroom Experience", slug: "ai-for-teachers", excerpt: "How educators leverage AI for better lesson plans and personalized learning.", content: "", cover_image_url: null, audience: "teachers", icon: "BookOpen", related_tool_ids: ["t1", "t21"], tags: ["teachers", "education"], view_count: 23400, is_featured: true, is_published: true, meta_title: null, meta_description: null, author_id: null, created_at: "2024-01-25", updated_at: "2024-01-25", published_at: "2024-01-25" },
  { id: "uc3", title: "AI for Marketers: Scaling Your Marketing Engine", slug: "ai-for-marketers", excerpt: "Learn how top marketing teams use AI for content and campaigns.", content: "", cover_image_url: null, audience: "marketers", icon: "TrendingUp", related_tool_ids: ["t1", "t4", "t20"], tags: ["marketing", "content"], view_count: 45600, is_featured: true, is_published: true, meta_title: null, meta_description: null, author_id: null, created_at: "2024-02-01", updated_at: "2024-02-01", published_at: "2024-02-01" },
  { id: "uc4", title: "AI for Developers: Supercharge Your Coding Workflow", slug: "ai-for-developers", excerpt: "Explore how developers are using AI to write better code faster.", content: "", cover_image_url: null, audience: "developers", icon: "Code", related_tool_ids: ["t11", "t12", "t13"], tags: ["development", "coding"], view_count: 56700, is_featured: true, is_published: true, meta_title: null, meta_description: null, author_id: null, created_at: "2024-02-10", updated_at: "2024-02-10", published_at: "2024-02-10" },
  { id: "uc5", title: "AI for Content Creators: Build Your Creative Empire", slug: "ai-for-content-creators", excerpt: "How creators use AI to produce more content and grow their audience.", content: "", cover_image_url: null, audience: "creators", icon: "Palette", related_tool_ids: ["t5", "t9", "t16"], tags: ["creators", "content"], view_count: 38900, is_featured: true, is_published: true, meta_title: null, meta_description: null, author_id: null, created_at: "2024-02-15", updated_at: "2024-02-15", published_at: "2024-02-15" },
  { id: "uc6", title: "AI for Business: Transform Your Operations", slug: "ai-for-business-operations", excerpt: "Discover how businesses implement AI to streamline operations.", content: "", cover_image_url: null, audience: "business", icon: "Building2", related_tool_ids: ["t1", "t18", "t22"], tags: ["business", "operations"], view_count: 29800, is_featured: false, is_published: true, meta_title: null, meta_description: null, author_id: null, created_at: "2024-03-01", updated_at: "2024-03-01", published_at: "2024-03-01" },
];

// ============================================================================
// COMPARISONS
// ============================================================================
export const comparisons: Comparison[] = [
  { id: "cm1", tool_a_id: "t1", tool_b_id: "t2", slug: "chatgpt-vs-claude", title: "ChatGPT vs Claude", summary: "A comprehensive comparison of OpenAI's ChatGPT and Anthropic's Claude across features, performance, pricing, and use cases.", verdict: "Both tools excel in different areas. ChatGPT offers more features and integrations, while Claude provides superior long-form analysis.", winner_id: null, view_count: 89400, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-20", updated_at: "2024-01-20" },
  { id: "cm2", tool_a_id: "t5", tool_b_id: "t6", slug: "midjourney-vs-dall-e-3", title: "Midjourney vs DALL-E 3", summary: "Comparing the two leading AI image generators on quality, ease of use, pricing, and creative control.", verdict: "Midjourney produces more artistic images, while DALL-E 3 excels at following precise instructions.", winner_id: "t5", view_count: 67800, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-01", updated_at: "2024-02-01" },
  { id: "cm3", tool_a_id: "t11", tool_b_id: "t12", slug: "github-copilot-vs-cursor", title: "GitHub Copilot vs Cursor", summary: "An in-depth comparison of the two most popular AI coding assistants for developers.", verdict: "Cursor offers a more integrated AI-first experience, while GitHub Copilot has broader IDE support.", winner_id: "t12", view_count: 45600, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-15", updated_at: "2024-02-15" },
  { id: "cm4", tool_a_id: "t1", tool_b_id: "t3", slug: "chatgpt-vs-gemini", title: "ChatGPT vs Gemini", summary: "Comparing OpenAI's ChatGPT with Google's Gemini across capabilities, pricing, and ecosystem.", verdict: "ChatGPT leads in integrations, while Gemini excels in multimodal tasks and Google ecosystem integration.", winner_id: null, view_count: 56700, is_published: true, meta_title: null, meta_description: null, created_at: "2024-03-01", updated_at: "2024-03-01" },
];

export const comparisonFeatures: ComparisonFeature[] = [
  { id: "cf1", comparison_id: "cm1", feature_name: "Context Window", category: "Capabilities", tool_a_value: "128K tokens", tool_b_value: "200K tokens", tool_a_score: 8, tool_b_score: 10, sort_order: 1, created_at: "2024-01-20" },
  { id: "cf2", comparison_id: "cm1", feature_name: "Code Generation", category: "Capabilities", tool_a_value: "Excellent", tool_b_value: "Excellent", tool_a_score: 9, tool_b_score: 9, sort_order: 2, created_at: "2024-01-20" },
  { id: "cf3", comparison_id: "cm1", feature_name: "Creative Writing", category: "Capabilities", tool_a_value: "Very Good", tool_b_value: "Excellent", tool_a_score: 8, tool_b_score: 9, sort_order: 3, created_at: "2024-01-20" },
  { id: "cf4", comparison_id: "cm1", feature_name: "Image Generation", category: "Features", tool_a_value: "DALL-E 3 Built-in", tool_b_value: "Not Available", tool_a_score: 10, tool_b_score: 0, sort_order: 4, created_at: "2024-01-20" },
  { id: "cf5", comparison_id: "cm1", feature_name: "Web Browsing", category: "Features", tool_a_value: "Yes", tool_b_value: "No", tool_a_score: 10, tool_b_score: 0, sort_order: 5, created_at: "2024-01-20" },
  { id: "cf6", comparison_id: "cm1", feature_name: "API Pricing", category: "Pricing", tool_a_value: "$0.03/1K tokens", tool_b_value: "$0.015/1K tokens", tool_a_score: 7, tool_b_score: 9, sort_order: 6, created_at: "2024-01-20" },
  { id: "cf7", comparison_id: "cm1", feature_name: "Safety", category: "Trust", tool_a_value: "Good", tool_b_value: "Excellent", tool_a_score: 7, tool_b_score: 10, sort_order: 7, created_at: "2024-01-20" },
  { id: "cf8", comparison_id: "cm1", feature_name: "Speed", category: "Performance", tool_a_value: "Fast", tool_b_value: "Very Fast", tool_a_score: 8, tool_b_score: 9, sort_order: 8, created_at: "2024-01-20" },
];

// ============================================================================
// RANKINGS
// ============================================================================
export const rankings: Ranking[] = [
  { id: "r1", title: "Best AI Tools of 2024", slug: "best-ai-tools-2024", description: "Our definitive ranking of the best AI tools across all categories.", category: "general", audience: null, icon: "Trophy", cover_image_url: null, methodology: "Rankings are based on user ratings, features, pricing, and community feedback.", view_count: 89400, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-15", updated_at: "2024-01-15", published_at: "2024-01-15" },
  { id: "r2", title: "Best Free AI Tools", slug: "best-free-ai-tools", description: "The top AI tools you can use completely free.", category: "free", audience: null, icon: "Gift", cover_image_url: null, methodology: "Ranked by free tier generosity and quality.", view_count: 67800, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-01-20", updated_at: "2024-01-20", published_at: "2024-01-20" },
  { id: "r3", title: "Best AI Tools for Students", slug: "best-ai-tools-for-students", description: "Top AI tools for academic success.", category: "education", audience: "students", icon: "GraduationCap", cover_image_url: null, methodology: "Evaluated on educational value and student pricing.", view_count: 45600, is_featured: true, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-01", updated_at: "2024-02-01", published_at: "2024-02-01" },
  { id: "r4", title: "Best AI Tools for Content Creators", slug: "best-ai-tools-for-creators", description: "The ultimate toolkit for content creators.", category: "creative", audience: "creators", icon: "Palette", cover_image_url: null, methodology: "Ranked by creative output quality and pricing.", view_count: 34500, is_featured: false, is_published: true, meta_title: null, meta_description: null, created_at: "2024-02-15", updated_at: "2024-02-15", published_at: "2024-02-15" },
];

export const rankingEntries: RankingEntry[] = [
  { id: "re1", ranking_id: "r1", tool_id: "t1", position: 1, score: 9.6, highlights: "The most versatile AI assistant", pros: ["Huge plugin ecosystem", "Multimodal capabilities", "Custom GPTs"], cons: ["Can be expensive", "Occasional hallucinations"], created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "re2", ranking_id: "r1", tool_id: "t2", position: 2, score: 9.4, highlights: "Best for long-form analysis and safety", pros: ["200K context window", "Excellent writing", "Strong safety"], cons: ["No image generation", "No web browsing"], created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "re3", ranking_id: "r1", tool_id: "t5", position: 3, score: 9.3, highlights: "Gold standard for AI image generation", pros: ["Stunning quality", "Active community", "Consistent style"], cons: ["Discord-only", "No free tier"], created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "re4", ranking_id: "r1", tool_id: "t11", position: 4, score: 9.1, highlights: "Essential AI coding companion", pros: ["IDE integration", "Code awareness", "Multi-language"], cons: ["Subscription required", "Sometimes inaccurate"], created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "re5", ranking_id: "r1", tool_id: "t16", position: 5, score: 9.0, highlights: "Most realistic AI voice synthesis", pros: ["Ultra-realistic voices", "Voice cloning", "Multi-language"], cons: ["Credit-based pricing", "Processing time"], created_at: "2024-01-15", updated_at: "2024-01-15" },
  { id: "re6", ranking_id: "r2", tool_id: "t1", position: 1, score: 9.2, highlights: "Generous free tier with GPT-3.5", pros: ["Free GPT-3.5 access", "Web browsing", "No credit card"], cons: ["Limited GPT-4", "Rate limits"], created_at: "2024-01-20", updated_at: "2024-01-20" },
  { id: "re7", ranking_id: "r2", tool_id: "t7", position: 2, score: 9.1, highlights: "Completely free and open-source", pros: ["Fully open-source", "Run locally", "No limits"], cons: ["Requires GPU", "Technical setup"], created_at: "2024-01-20", updated_at: "2024-01-20" },
  { id: "re8", ranking_id: "r2", tool_id: "t3", position: 3, score: 9.0, highlights: "Google's powerful free AI model", pros: ["Free Gemini Pro", "Google integration", "Multimodal"], cons: ["Limited advanced features"], created_at: "2024-01-20", updated_at: "2024-01-20" },
];

// ============================================================================
// NEWS
// ============================================================================
export const news: NewsArticle[] = [
  { id: "n1", title: "OpenAI Launches GPT-5 with Revolutionary Reasoning Capabilities", slug: "openai-launches-gpt5-reasoning", excerpt: "OpenAI has unveiled GPT-5, featuring breakthrough reasoning capabilities that significantly outperform previous models.", content: "", cover_image_url: null, source_name: "OpenAI Blog", source_url: "https://openai.com/blog", author_id: null, tags: ["openai", "gpt-5", "language model"], related_tool_ids: ["t1"], view_count: 123400, is_featured: true, is_published: true, is_breaking: true, meta_title: null, meta_description: null, created_at: "2024-03-10", updated_at: "2024-03-10", published_at: "2024-03-10" },
  { id: "n2", title: "Google DeepMind Achieves Breakthrough in AI Video Generation", slug: "google-deepmind-ai-video-breakthrough", excerpt: "Google DeepMind's latest video generation model produces cinema-quality videos from text.", content: "", cover_image_url: null, source_name: "DeepMind", source_url: "https://deepmind.google", author_id: null, tags: ["google", "deepmind", "video"], related_tool_ids: ["t3"], view_count: 89400, is_featured: true, is_published: true, is_breaking: false, meta_title: null, meta_description: null, created_at: "2024-03-08", updated_at: "2024-03-08", published_at: "2024-03-08" },
  { id: "n3", title: "Anthropic Introduces Claude 4 with Enhanced Tool Use", slug: "anthropic-claude-4-enhanced-tool-use", excerpt: "Anthropic releases Claude 4 with dramatically improved tool use capabilities.", content: "", cover_image_url: null, source_name: "Anthropic", source_url: "https://anthropic.com", author_id: null, tags: ["anthropic", "claude", "tool use"], related_tool_ids: ["t2"], view_count: 67800, is_featured: false, is_published: true, is_breaking: false, meta_title: null, meta_description: null, created_at: "2024-03-05", updated_at: "2024-03-05", published_at: "2024-03-05" },
  { id: "n4", title: "Midjourney V7 Sets New Standard for AI Art Quality", slug: "midjourney-v7-new-standard-ai-art", excerpt: "Midjourney releases Version 7 with photorealistic rendering and enhanced creative controls.", content: "", cover_image_url: null, source_name: "Midjourney", source_url: "https://midjourney.com", author_id: null, tags: ["midjourney", "image generation"], related_tool_ids: ["t5"], view_count: 56700, is_featured: false, is_published: true, is_breaking: false, meta_title: null, meta_description: null, created_at: "2024-03-01", updated_at: "2024-03-01", published_at: "2024-03-01" },
  { id: "n5", title: "EU AI Act Implementation Begins: What You Need to Know", slug: "eu-ai-act-implementation-guide", excerpt: "The EU AI Act is now being implemented with new compliance requirements.", content: "", cover_image_url: null, source_name: "European Commission", source_url: "https://ec.europa.eu", author_id: null, tags: ["regulation", "eu", "ai act"], related_tool_ids: [], view_count: 45600, is_featured: false, is_published: true, is_breaking: false, meta_title: null, meta_description: null, created_at: "2024-02-25", updated_at: "2024-02-25", published_at: "2024-02-25" },
  { id: "n6", title: "Microsoft Copilot Expands to All Office 365 Users", slug: "microsoft-copilot-office-365-expansion", excerpt: "Microsoft makes Copilot available to all Office 365 subscribers worldwide.", content: "", cover_image_url: null, source_name: "Microsoft", source_url: "https://microsoft.com", author_id: null, tags: ["microsoft", "copilot", "office"], related_tool_ids: [], view_count: 34500, is_featured: true, is_published: true, is_breaking: false, meta_title: null, meta_description: null, created_at: "2024-03-09", updated_at: "2024-03-09", published_at: "2024-03-09" },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================
export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((t) => t.id === id);
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  const category = categories.find((c) => c.slug === categorySlug);
  if (!category) return [];
  return tools.filter((t) => t.category_id === category.id);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.is_featured).sort((a, b) => b.upvote_count - a.upvote_count);
}

export function getTrendingTools(): Tool[] {
  return [...tools].sort((a, b) => b.upvote_count - a.upvote_count).slice(0, 10);
}

export function getToolPricing(toolId: string): ToolPricing[] {
  return toolPricing.filter((p) => p.tool_id === toolId).sort((a, b) => a.sort_order - b.sort_order);
}

export function getComparisonBySlug(slug: string): Comparison | undefined {
  return comparisons.find((c) => c.slug === slug);
}

export function getComparisonFeatures(comparisonId: string): ComparisonFeature[] {
  return comparisonFeatures.filter((f) => f.comparison_id === comparisonId).sort((a, b) => a.sort_order - b.sort_order);
}

export function getRankingBySlug(slug: string): Ranking | undefined {
  return rankings.find((r) => r.slug === slug);
}

export function getRankingEntries(rankingId: string): (RankingEntry & { tool: Tool })[] {
  return rankingEntries
    .filter((e) => e.ranking_id === rankingId)
    .sort((a, b) => a.position - b.position)
    .map((entry) => ({
      ...entry,
      tool: tools.find((t) => t.id === entry.tool_id)!,
    }));
}

export function getPromptsByCategory(categorySlug: string): Prompt[] {
  const category = promptCategories.find((c) => c.slug === categorySlug);
  if (!category) return [];
  return prompts.filter((p) => p.category_id === category.id);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.tagline.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q)
  );
}
